import { sb, sbOk, getCurrentCompanyId } from "../shared.js";
import { uploadBase64ToStorage } from "../offline/storageUpload.js";

// ---------- ثابت‌ها ----------

export const SOURCE_OPTIONS = [
  { value: "bowtie", label: "BowTie" },
  { value: "risk_assessment", label: "ارزیابی ریسک" },
  { value: "incident", label: "حوادث" },
  { value: "near_miss", label: "شبه حوادث" },
  { value: "medical_exam", label: "معاینات پزشکی" },
  { value: "workplace_hazard", label: "عوامل زیان‌آور محیط کار" },
  { value: "proactive_indicator", label: "شاخص‌های Proactive HSE" },
  { value: "audit", label: "ممیزی" },
  { value: "other", label: "سایر" },
];

export const PRIORITY_OPTIONS = [
  { value: "low", label: "پایین", color: "#166534", bg: "#dcfce7" },
  { value: "medium", label: "متوسط", color: "#92400e", bg: "#fef3c7" },
  { value: "high", label: "بالا", color: "#c92a2a", bg: "#fee2e2" },
  { value: "critical", label: "بحرانی", color: "#fff", bg: "#7c2d12" },
];

// ترتیب عمداً همان ترتیب گردش‌کار طبیعی است: باز → در حال انجام → انجام‌شده
// منتظر تأیید → بسته‌شده. «منقضی‌شده» جدا نگه داشته شده چون یک وضعیتِ
// «به‌جای» است، نه ادامه‌ی طبیعی گردش‌کار.
export const STATUS_META = {
  open: { label: "باز / انجام نشده", emoji: "🔴", color: "#fff", bg: "#dc2626" },
  in_progress: { label: "در حال انجام", emoji: "🟠", color: "#fff", bg: "#f97316" },
  done_pending_approval: { label: "انجام شده، منتظر تأیید HSE", emoji: "🟡", color: "#1f2937", bg: "#facc15" },
  closed: { label: "تأیید و بسته شده", emoji: "🟢", color: "#fff", bg: "#16a34a" },
  expired: { label: "منقضی شده", emoji: "⚫", color: "#fff", bg: "#374151" },
};
export const STATUS_ORDER = ["open", "in_progress", "done_pending_approval", "closed", "expired"];

// آیا این اقدام از نظر مهلت، «سررسید شده» است؟ — یک وضعیتِ محاسبه‌شده، نه
// یک ستون در دیتابیس: یعنی مهلت گذشته ولی هنوز به‌طور رسمی بسته/منقضی
// اعلام نشده (برخلاف status="expired" که یک تصمیم صریح است)
export function isOverdue(action) {
  if (!action.dueDate) return false;
  if (action.status === "closed" || action.status === "expired") return false;
  return new Date(action.dueDate) < new Date(new Date().toDateString());
}

// ---------- نگاشت رکورد ----------

function fromRow(r) {
  return {
    id: r.id,
    actionNumber: r.action_number || "",
    source: r.source || "other",
    registeredAt: r.registered_at,
    nonconformanceDescription: r.nonconformance_description || "",
    rootCause: r.root_cause || "",
    actionDescription: r.action_description || "",
    responsibleContractorId: r.responsible_contractor_id || "",
    responsibleContractorName: r.responsible_contractor_name || "",
    responsiblePerson: r.responsible_person || "",
    projectName: r.project_name || "",
    dueDate: r.due_date || "",
    priority: r.priority || "medium",
    status: r.status || "open",
    completedAt: r.completed_at || "",
    executorNotes: r.executor_notes || "",
    attachments: Array.isArray(r.attachments) ? r.attachments : [],
    approvedBy: r.approved_by || "",
    approvedAt: r.approved_at || "",
    approverNotes: r.approver_notes || "",
    linkedAnomalyId: r.linked_anomaly_id || "",
    linkedBarrierId: r.linked_barrier_id || "",
    linkedBowtieId: r.linked_bowtie_id || "",
    linkedAssessmentId: r.linked_assessment_id || "",
    autoGenerated: !!r.auto_generated,
    createdBy: r.created_by || "",
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

function toDb(rec) {
  return {
    action_number: rec.actionNumber || null,
    source: rec.source || "other",
    nonconformance_description: rec.nonconformanceDescription || null,
    root_cause: rec.rootCause || null,
    action_description: rec.actionDescription || null,
    responsible_contractor_id: rec.responsibleContractorId || null,
    responsible_contractor_name: rec.responsibleContractorName || null,
    responsible_person: rec.responsiblePerson || null,
    project_name: rec.projectName || null,
    due_date: rec.dueDate || null,
    priority: rec.priority || "medium",
    status: rec.status || "open",
    completed_at: rec.completedAt || null,
    executor_notes: rec.executorNotes || null,
    attachments: rec.attachments || [],
    approved_by: rec.approvedBy || null,
    approved_at: rec.approvedAt || null,
    approver_notes: rec.approverNotes || null,
    linked_anomaly_id: rec.linkedAnomalyId || null,
    linked_barrier_id: rec.linkedBarrierId || null,
    linked_bowtie_id: rec.linkedBowtieId || null,
    linked_assessment_id: rec.linkedAssessmentId || null,
    auto_generated: !!rec.autoGenerated,
  };
}

// ---------- CRUD ----------

export async function loadCorrectiveActions() {
  const companyId = getCurrentCompanyId();
  const filter = companyId ? `&company_id=eq.${companyId}` : "";
  const rows = await sb(`corrective_actions?select=*&order=created_at.desc${filter}`);
  return (sbOk(rows) ? rows : []).map(fromRow);
}

// جلوگیری از تکرار: آیا برای این ارزیابی از قبل یک اقدام اصلاحی صادر شده؟
export async function loadCorrectiveActionForAssessment(assessmentId) {
  if (!assessmentId) return null;
  const rows = await sb(`corrective_actions?linked_assessment_id=eq.${assessmentId}&select=*&order=created_at.desc&limit=1`);
  return sbOk(rows) && rows.length > 0 ? fromRow(rows[0]) : null;
}

// نسخه‌ی دسته‌ای — برای صفحه‌ی نتایج که همزمان چند ارزیابی را لیست می‌کند
// (جلوگیری از N+1 کوئری). خروجی: نگاشت assessmentId -> اقدام اصلاحی
export async function loadCorrectiveActionsForAssessments(assessmentIds) {
  if (!assessmentIds || assessmentIds.length === 0) return {};
  const idList = assessmentIds.map((id) => `"${id}"`).join(",");
  const rows = await sb(`corrective_actions?linked_assessment_id=in.(${idList})&select=*&order=created_at.desc`);
  const map = {};
  if (sbOk(rows)) {
    rows.forEach((r) => {
      // اولین (جدیدترین، چون قبلاً desc مرتب شده) برای هر ارزیابی کافی است
      if (!map[r.linked_assessment_id]) map[r.linked_assessment_id] = fromRow(r);
    });
  }
  return map;
}

export async function createCorrectiveAction(rec, createdBy, explicitCompanyId) {
  const companyId = explicitCompanyId || getCurrentCompanyId();
  // شماره‌ی خودکار: CA-<تعداد فعلی + 1> — برای شمارش دقیق‌تر، تعداد رکوردهای
  // همین شرکت را می‌خوانیم؛ اگر کاربر خودش شماره‌ای وارد کرده باشد، همان حفظ می‌شود.
  let actionNumber = rec.actionNumber?.trim();
  if (!actionNumber) {
    const countRows = await sb(`corrective_actions?select=id${companyId ? `&company_id=eq.${companyId}` : ""}`);
    const nextSeq = (sbOk(countRows) ? countRows.length : 0) + 1;
    actionNumber = `CA-${String(nextSeq).padStart(4, "0")}`;
  }
  const payload = { ...toDb({ ...rec, actionNumber }), company_id: companyId, created_by: createdBy || "" };
  const rows = await sb("corrective_actions", { method: "POST", body: JSON.stringify([payload]) });
  if (!sbOk(rows)) return { __error: true, message: "خطا در ثبت: " + (rows?.message || "نامشخص") };
  return fromRow(rows[0]);
}

export async function updateCorrectiveAction(id, rec) {
  const payload = toDb(rec);
  payload.updated_at = new Date().toISOString();
  const rows = await sb(`corrective_actions?id=eq.${id}`, { method: "PATCH", body: JSON.stringify(payload) });
  if (!sbOk(rows)) return { __error: true, message: "خطا در ذخیره‌سازی: " + (rows?.message || "نامشخص") };
  return fromRow(rows[0]);
}

export async function deleteCorrectiveAction(id) {
  const result = await sb(`corrective_actions?id=eq.${id}`, { method: "DELETE", prefer: "return=minimal" });
  if (!sbOk(result)) return { __error: true, message: "خطا در حذف" };
  return { ok: true };
}

// تأیید نهایی HSE/کارفرما — وضعیت را به «بسته‌شده» می‌برد
export async function approveCorrectiveAction(id, approvedBy, approverNotes) {
  return updateCorrectiveAction(id, {
    status: "closed",
    approvedBy,
    approvedAt: new Date().toISOString(),
    approverNotes: approverNotes || "",
  });
}

// ---------- اتصال به موتور اثربخشی BowTie (فاز ۴) ----------
// آیا همین الان یک اقدام اصلاحیِ «باز» (هر وضعیتی جز بسته‌شده) برای این
// Barrier وجود دارد؟ — پایه‌ی جلوگیری از تکرار در بازمحاسبه‌های بعدی.
export async function findOpenCorrectiveActionForBarrier(barrierId) {
  const companyId = getCurrentCompanyId();
  const filter = companyId ? `&company_id=eq.${companyId}` : "";
  const rows = await sb(`corrective_actions?linked_barrier_id=eq.${barrierId}&status=neq.closed${filter}&select=id&limit=1`);
  return sbOk(rows) && rows.length > 0 ? rows[0].id : null;
}

// اقدام اصلاحی خودکار برای یک Barrier که اثربخشی‌اش از حد مجاز پایین‌تر
// آمده — عمداً از همان createCorrectiveAction موجود استفاده می‌کند (همان
// شماره‌گذاری خودکار CA-xxxx، همان اسکوپ company_id) تا هیچ مسیر جدیدی
// در ساختار داده باز نشود؛ فقط چند فیلد اضافه (اتصال به بریر/بوتای،
// auto_generated) را با خودش حمل می‌کند.
export async function createAutoCorrectiveActionForBarrier({ barrierId, barrierLabel, bowtieId, bowtieTitle, score, companyId }) {
  const existingId = await findOpenCorrectiveActionForBarrier(barrierId);
  if (existingId) return { skipped: true, reason: "duplicate", existingId };

  const priority = score < 40 ? "critical" : "high";
  const rec = {
    source: "bowtie",
    nonconformanceDescription: `کاهش خودکار اثربخشی Barrier «${barrierLabel}» در BowTie «${bowtieTitle}» به ${score}٪ (کمتر از حد مجاز تعیین‌شده برای این کنترل)`,
    rootCause: "افزایش شواهد Anomaly مرتبط با این Barrier و/یا باز ماندن اقدامات اصلاحی پیشین مرتبط با همان شواهد",
    actionDescription: "بازبینی و تقویت این کنترل (Barrier) توسط HSE موردنیاز است.",
    priority,
    status: "open",
    linkedBarrierId: barrierId,
    linkedBowtieId: bowtieId,
    autoGenerated: true,
  };
  // اگر company_id واقعیِ BowTie در دسترس بود، صریحاً همان استفاده می‌شود
  // (نه company_id نشست فعلی) — ورودی سوم createCorrectiveAction برای
  // همین منظور اضافه شده؛ اگر ارسال نشود، به رفتار قبلی (نشست فعلی) برمی‌گردد.
  const created = await createCorrectiveAction(rec, "سیستم — تولید خودکار (افت اثربخشی Barrier)", companyId);
  if (created?.__error) return created;
  return { ok: true, created };
}

// ---------- آپلود پیوست (Storage) ----------

export async function uploadCorrectiveActionFile(base64Data, fileName, contentType) {
  const path = `${Date.now()}-${fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`;
  try {
    const url = await uploadBase64ToStorage("corrective-action-files", path, base64Data, contentType);
    return { name: fileName, url };
  } catch (e) {
    return { __error: true, message: e?.message || "خطا در آپلود فایل" };
  }
}

// ---------- کمکی: لیست پیمانکاران برای dropdown «شرکت/پیمانکار مسئول» ----------
// عمداً مستقل از loadContractors در App.jsx (که export نشده) — فقط همان
// دو فیلدی که برای این dropdown لازم است را می‌خواند.
export async function loadContractorsForDropdown() {
  const companyId = getCurrentCompanyId();
  const filter = companyId ? `&company_id=eq.${companyId}` : "";
  const rows = await sb(`contractors?select=id,name&order=name.asc${filter}`);
  return sbOk(rows) ? rows.map((r) => ({ id: r.id, name: r.name })) : [];
}

// ---------- KPI ----------

export function computeKpis(actions) {
  const kpis = { total: actions.length, open: 0, in_progress: 0, done_pending_approval: 0, closed: 0, expired: 0, overdue: 0 };
  actions.forEach((a) => {
    if (kpis[a.status] !== undefined) kpis[a.status] += 1;
    if (isOverdue(a)) kpis.overdue += 1;
  });
  return kpis;
}
